version: '2.4'

services:

  php:
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/srv/www/api
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  database:
    build:
      context: ./docker/database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/database/data.sql:/docker-entrypoint-inidb.d/data.sql
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/database/mysql_data:/var/lib/mysql
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge